/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as CookbookRouteImport } from './routes/cookbook'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookRoute = CookbookRouteImport.update({
  id: '/cookbook',
  path: '/cookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cookbook' | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cookbook' | '/workouts'
  id: '__root__' | '/' | '/cookbook' | '/workouts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookbookRoute: typeof CookbookRoute
  WorkoutsRoute: typeof WorkoutsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook': {
      id: '/cookbook'
      path: '/cookbook'
      fullPath: '/cookbook'
      preLoaderRoute: typeof CookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookbookRoute: CookbookRoute,
  WorkoutsRoute: WorkoutsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
